### ISSUE TITLE
Performance

### ISSUE THREAD

**Issue by Leeds-eBooks** [testdouble/scripty#34]
Is it possible that using scripty over a raw npm script would affect performance negatively? I'm seeing a ~10% performance hit and the only thing I'm changing is whether I'm using scripty or not. Sorry I don't have any solid data/benchmarks for this 😕

**Comment by searls** [comment]
Well, it definitely adds a level of indirection, and it does some File I/O to figure out which scripts to spawn, so I'd expect there to be some start-up hit. As for long-running scripts, I can't imagine what'd cause it to be any slower than `npm run` since that's also shelling out to a sub-process with `child_process.spawn`.

I'll close for now in lieu of solid benchmarks / profiling indicating something we can do to improve or optimize scripty.

**Comment by Leeds-eBooks** [comment]
Ok thanks for replying, I'll keep an eye on it and if it does seem to be a serious issue I'll run some proper benchmarks.
