### ISSUE TITLE
Scripty scripts are missing from the output of `npm run`

### ISSUE THREAD

**Issue by deanius** [testdouble/scripty#41]
For discoverability, developers expect available scripts to be listed from `npm run`. It appeared to me that scripty scripts are not - is that expected behavior?

Dean

**Comment by searls** [comment]
To try and get clarity here, this is what I get when I run `npm run` without args on [this branch](https://github.com/testdouble/testdouble.js/pull/100) of one of my projects:

```
$ npm run
Lifecycle scripts included in testdouble:
  test
    scripty
  preversion
    scripty
  postversion
    scripty
  version
    scripty
  prepublish
    scripty

available via `npm run-script`:
  clean:dist
    scripty
  clean
    scripty
  compile:node
    scripty
  compile:test
    scripty
  compile:browser
    scripty
  compile
    scripty
  test:cover:instrument
    scripty
  test:cover:run
    scripty
  test:cover:report
    scripty
  test:cover
    scripty
  test:browser
    scripty
  test:example:webpack
    scripty
  test:example:node
    scripty
  test:example:lineman
    scripty
  test:example
    scripty
  test:all
    scripty
  test:ci
    scripty
  version:write
    scripty
  version:changelog
    scripty
```

Since `npm` owns the `npm run` command, I'm not sure what I could do to override its behavior short of wrapping the `npm` bin, which nobody would get behind.

Do you have any insight into how this could be improved cleanly?

**Comment by zeke** [comment]
Shameless self-promotion and not a solution per se, but I prefer [npe](https://github.com/zeke/npe) to `npm run`.

```sh
npm i -g npe && npe scripts
```

**Comment by deanius** [comment]
Closing on account of my not remembering what I thought the problem was with that output, which LGTM.

**Comment by searls** [comment]
Haha ok dean
