### ISSUE TITLE
Sharable scripts via a npm package

### ISSUE THREAD

**Issue by thoov** [testdouble/scripty#68]
**Is there a way to *easily* share scripty scripts via a npm package?**

We have a need to share a set of common scripts with some internal teams and we could like to do that via a normal npm package.

You can think of a workflow like:

```shell
yarn add common-scripts
```

This package will contain binaries that are exported to either `node_modules/.bin` or have them defined in `node_modules/common-scripts/scripts`. Then the teams can simply defined there command to look like:

```json
{
  "scripts": {
    "build": "scripty"
  }
}
```

And of course run it like normal:

```shell
yarn build
```

Currently we modify the scripty property in package.json to hack this together:

```json
"scripty": {
  "path": "node_modules/common-scripts/scripts"
}
```

This has a couple of problems:

1. Can only reference one package (you could see a world where we might want to have multiple npm packages that teams install that separate the scripts by some kind of domain seperation)
2. If you change the path you cannot have "local" scripts that override external ones. Teams should be able to define a local executable that will override an external one.

Some potential ideas would be to have scripty look into `node_modules/.bin` if it cant find an executable that is already defined in `./scripts`. Another one would be to make path an array. I would like to hear your thoughts on this and if this sounds alright I can help implement the change if need be.

cc: @stefanpenner

**Comment by searls** [comment]
First, forgive me. I haven't had to change scripty hardly at all since first publishing it, so I'm not going to be thinking of edge cases this might impact

> Some potential ideas would be to have scripty look into node_modules/.bin 

Seems like a reasonable idea

> Another one would be to make path an array.

This also seems reasonable.

Another idea would be to add a configuration property (`scripty.modules`?) of names of packages in which scripty should automatically look add `scripts/` to its list of paths (e.g. `${require.resolve('blah')}/scripts`), so that you don't have to make assumptions about where the module will land on disk or type out "node_modules" a bunch of times. That way it's still declarative (instead of too magic)

**Comment by stefanpenner** [comment]
@searls glad to hear you are not immediately put off by this idea. I think it could be really powerful for scripty!

**Comment by thoov** [comment]
Closing as #69 has been merged
